licenses(["notice"]) # BSD
load("//bzl:rules_fest.bzl", "make_libraries")

make_libraries(
    deps = [
        "//festival/src/include",
    ],
    DIRNAME="src/modules/Intonation",
    H = "",
    SRCS = "int_aux.cc duffint.cc simple.cc gen_int.cc int_tree.cc",
)
