/* This file is autogenerated by Bazel rule src/modules:_init_modules */

#include "EST_unix.h"
#include "stdio.h"
#include "festival.h"

{Initialization_Declarations}

void festival_init_modules(void) {
     {Initialization_Calls}
}
