licenses(["notice"]) # BSD
load("//bzl:rules_fest.bzl", "make_libraries")

make_libraries(
    deps = [
        "//festival/src/include",
    ],
    DIRNAME="src/modules/Duration",
    H = "durationP.h",
    SRCS = "dur_aux.cc duration.cc Klatt.cc",
)
