licenses(["notice"]) # BSD

cc_library(
    name = "include",
    deps = [
        "//speech_tools/include",
    ],
    hdrs = glob(["**/*.h"]),
    includes = [""],
    visibility = ["//visibility:public"],
)
